### ISSUE TITLE
Merge Error happens - QM not found

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-cp-queue-manager#10]
updated workflow and test completed. Merge PR and test fails with the following message

Error from server (NotFound): configmaps "oms-queue-config" not found
Error from server (NotFound): queuemanagers.mq.ibm.com "telco-cloud" not found
Waiting for Queue Manager/telco-cloud in gitops-cp-queue-manager
Error from server (NotFound): queuemanagers.mq.ibm.com "telco-cloud" not found
Waiting for Queue Manager/telco-cloud in gitops-cp-queue-manager
Error from server (NotFound): queuemanagers.mq.ibm.com "telco-cloud" not found

**Comment by gowdhaman-j** [comment]
GH Action Successfully executed and found the below status in GH Actions
[pages build and deployment]
